import "./globals.css";
import { Inter } from "next/font/google";
import Background from "../public/background.png";

// components
import Navbar from "./components/Navbar/Navbar";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="absolute inset-0 z-[-1] bg-black">
          <Image
            src={Background}
            alt="Background logo"
            layout="fill"
            objectFit="cover"
            className="w-full"
            draggable={false}
          />
        </div>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
